// export interface DicomSimplifiedTags {
// {
//   "AccessionNumber": "0071351232",
//   "AcquisitionDate": "20180801",
//   "AcquisitionDuration": null,
//   "AcquisitionMatrix": "0\\256\\128\\0",
//   "AcquisitionNumber": "1",
//   "AcquisitionTime": "130104",
//   "ActualReceiveGainAnalog": null,
//   "ActualReceiveGainDigital": null,
//   "ActualSeriesDataTimeStamp": null,
//   "AdditionalAssetData": "10000\\0\\-1\\0\\\\NO\\ ",
//   "AdditionalPatientHistory": "",
//   "AdvantageCompOverflow": null,
//   "AdvantageCompUnderflow": null,
//   "AnalogReceiverGain": null,
//   "AnatomicRegionSequence": [
//     {
//       "CodeMeaning": "Head",
//       "CodeValue": "T-D1100",
//       "CodingSchemeDesignator": "SRT"
//     }
//   ],
//   "AngioFlag": "N",
//   "AssetRFactors": "1\\1 ",
//   "AutoWindowLevelAlpha": "0 ",
//   "AutoWindowLevelBeta": "0 ",
//   "AutoWindowLevelLevel": "0 ",
//   "AutoWindowLevelWindow": "0 ",
//   "BitmapDefiningCVs": null,
//   "BitmapOfPrescanOptions": null,
//   "BitsAllocated": "16",
//   "BitsStored": "16",
//   "BodyPartExamined": "HEAD",
//   "CalibratedFieldStrength": null,
//   "CardiacNumberOfImages": "0",
//   "CardiacPhases": null,
//   "CardiacRepetitionTime": "0.000000",
//   "CenterFrequency": "1277717830",
//   "CoilIDData": "A:0\\P1:0\\P2:0\\P3:\\GEHCR9WJoi2N8R6oHxmCyUY0RfaWNgK8\\9300000014b9100f\\P4:\\GEHCj8bduuefZwrQQNpxnXge7VDzZ3BW\\9200000014beda0f ",
//   "Columns": "256",
//   "ConcatenatedSAT": "0.000000",
//   "ContentDate": "20180801",
//   "ContentQualification": "PRODUCT ",
//   "ContentTime": "130104",
//   "Contiguous": null,
//   "DelayAfterTrigger": "0 ",
//   "DeviceSerialNumber": "000000HU1039MR05",
//   "DigitalReceiverGain": null,
//   "DisplayFieldOfView": "300.000000",
//   "EchoNumbers": "1",
//   "EchoTime": "2.1",
//   "EchoTrainLength": "1",
//   "EffectiveEchoSpacing": null,
//   "EquipmentUID": "1.2.840.113619.1.410.5.4722639.4348271",
//   "ExtremityCoilFlag": null,
//   "FastPhases": null,
//   "FirstScanLocation": "-20 ",
//   "FirstScanRAS": "I ",
//   "FlipAngle": "30",
//   "FloatSlop": "0.000000",
//   "ForeignImageRevision": "",
//   "FractionalEcho": null,
//   "FrameOfReferenceUID": "1.2.840.113619.2.410.4722639.4348271.18936.1532629476.529",
//   "GECoilName": "C-Head+Neck 40",
//   "GEImageIntegrity": null,
//   "GoverningBodydBdtAndSARDefinition": "IEC\\IEC_FIRST_LEVEL\\IEC_FIRST_LEVEL ",
//   "GradientOffsetInX": null,
//   "GradientOffsetInY": null,
//   "GradientOffsetInZ": null,
//   "GraphicallyPrescribed": null,
//   "HeartRate": "0",
//   "HighBit": "15",
//   "HistogramTables": null,
//   "HorizontalFrameOfReference": "1783.000000 ",
//   "ImageActualDate": null,
//   "ImageArchiveFlag": null,
//   "ImageDimensionX": null,
//   "ImageDimensionY": null,
//   "ImageFilteringParameters": "\\\\1.5 0.2 0.2 3 64 0.6 1.5\\1.5 0.2 0.2 4 64 0.6 1.5\\1.5 0.2 0.2 6 64 0.6 1.5\\100\\0\\0\\ ",
//   "ImageFromWhichPrescribed": null,
//   "ImageLocation": null,
//   "ImageOrientationPatient": "1\\-0\\0\\-0\\1\\0",
//   "ImagePositionPatient": "-149.414\\-169.414\\-20",
//   "ImageType": "ORIGINAL\\PRIMARY\\OTHER",
//   "ImagedNucleus": "1H",
//   "ImagesInAcquisition": "9",
//   "ImagesInSeries": null,
//   "ImagesPerCardiacCycle": null,
//   "ImagingFrequency": "127.771783",
//   "ImagingMode": null,
//   "ImagingOptions": null,
//   "InPlanePhaseEncodingDirection": "ROW",
//   "IndicatesIfStudyHasCompleteInfo": null,
//   "IndicatesNumberOfUpdatesToHeader": null,
//   "InstanceNumber": "1",
//   "InstitutionName": "AFFIDEA SZEGED",
//   "IntegerSlop": null,
//   "InternalPulseSequenceName": "FGRE",
//   "LandmarkCounter": null,
//   "LargestImagePixelValue": "2126",
//   "LastImageNumberUsed": null,
//   "LastPseq": null,
//   "LastPulseSequenceUsed": null,
//   "LastScanLocation": "20",
//   "LastScanRAS": "S ",
//   "Laterality": "",
//   "LevelValue": null,
//   "LimitsInUnitsOfPercent": "100.000000",
//   "LocationsInAcquisition": null,
//   "LowerRangeOfPixels": null,
//   "MRAcquisitionType": "2D",
//   "MagneticFieldStrength": "3",
//   "Manufacturer": "GE MEDICAL SYSTEMS",
//   "ManufacturerModelName": "DISCOVERY MR750w",
//   "MobileLocationNumber": "9999",
//   "Modality": "MR",
//   "NameOfPhysiciansReadingStudy": "KINCSES TAMAS DR.",
//   "NegScanSpacing": null,
//   "NumberOfAcquisitions": null,
//   "NumberOfAverages": "1",
//   "NumberOfEPIShots": null,
//   "NumberOfEchos": null,
//   "NumberOfExcitations": null,
//   "NumberOfImagesArchived": null,
//   "NumberOfUpdatesToHeader": null,
//   "OffsetFrequency": "0 ",
//   "OperatorsName": "TA",
//   "PSDEstimatedLimit": "35.264820 ",
//   "PSDEstimatedLimitInTeslaPerSecond": "0.000000",
//   "PatientAge": "064Y",
//   "PatientBirthDate": "19540707",
//   "PatientID": "067841015",
//   "PatientName": "Beck^Ferencné",
//   "PatientPosition": "FFS",
//   "PatientSex": "W",
//   "PatientWeight": "79",
//   "PauseInterval": null,
//   "PeakRateOfChangeOfGradientField": "0.000000",
//   "PeakSAR": "0.475261",
//   "PercentPhaseFieldOfView": "100",
//   "PercentSampling": "100",
//   "PerformedLocation": "HSZR",
//   "PerformedProcedureStepDescription": "KOPONYA SM",
//   "PerformedProcedureStepID": "4341.1533121257",
//   "PerformedProcedureStepStartDate": "20180801",
//   "PerformedProcedureStepStartTime": "130057",
//   "PerformedStationName": "HSZRMR02",
//   "PhotometricInterpretation": "MONOCHROME2",
//   "PixelBandwidth": "244.141",
//   "PixelData": null,
//   "PixelRepresentation": "1",
//   "PixelSpacing": "1.1719\\1.1719",
//   "PlaneType": null,
//   "PositionReferenceIndicator": "",
//   "PrescanReuseString": "",
//   "PrescanStatus": null,
//   "PrescanType": null,
//   "PrescribedFlowAxis": null,
//   "PrimaryReceiverSuiteAndHost": "HSZRMR02",
//   "PrivateCreator": "GEMS_PARM_01",
//   "PrivateInPlanePhaseEncodingDirection": "ROW ",
//   "ProductId": "SIGNA ",
//   "ProjectionAlgorithm": "",
//   "ProjectionAngle": "0.000000",
//   "ProtocolName": "* Koponya MS rutin (foll",
//   "PulseSequence": null,
//   "PulseSequenceDate": "20161206233707",
//   "PulseSequenceMode": null,
//   "PulseSequenceName": "fgre",
//   "PulseTime": "0.000000",
//   "RASLetterOfImageLocation": "I ",
//   "RawDataRunNumber": null,
//   "RawDataType": null,
//   "ReceiveCoilName": "Head+Neck 40",
//   "ReconModeFlagWord": null,
//   "ReconstructionDiameter": "300",
//   "ReferencedPerformedProcedureStepSequence": [
//     {
//       "ReferencedSOPClassUID": "1.2.840.10008.3.1.2.3.3",
//       "ReferencedSOPInstanceUID": "1.2.840.113619.6.410.65157580390904166261885844408799328666"
//     }
//   ],
//   "ReferringPhysicianName": "",
//   "RepetitionTime": "6.412",
//   "RequestAttributesSequence": [
//     {
//       "RequestedProcedureDescription": "KOPONYA",
//       "RequestedProcedureID": "0071351232",
//       "ScheduledProcedureStepDescription": "KOPONYA",
//       "ScheduledProcedureStepID": "0071351232",
//       "ScheduledProtocolCodeSequence": [
//         {
//           "CodeMeaning": "KOPONYA",
//           "CodeValue": "6000",
//           "CodingSchemeDesignator": "99GAP"
//         }
//       ]
//     }
//   ],
//   "RespiratoryRateInBPM": null,
//   "RespiratoryTriggerPoint": null,
//   "RotationFromSourceXRot": "0.000000",
//   "RotationFromSourceYRot": "0.000000",
//   "RotationFromSourceZRot": "0.000000",
//   "Rows": "256",
//   "SAR": "0.23763",
//   "SARDefinition": "WHOLE_BODY_6_MIN\\LOCAL_PEAK_6_MIN\\PARTIAL_BODY_6MIN ",
//   "SARValue": "0.2376\\0.475261\\0.23763 ",
//   "SATFatWaterBone": null,
//   "SATLocationA": null,
//   "SATLocationF": null,
//   "SATLocationH": null,
//   "SATLocationL": null,
//   "SATLocationP": null,
//   "SATLocationR": null,
//   "SATThicknessAP": null,
//   "SATThicknessHF": null,
//   "SATThicknessRL": null,
//   "SOPClassUID": "1.2.840.10008.5.1.4.1.1.4",
//   "SOPInstanceUID": "1.2.840.113619.2.410.4722639.4348271.15442.1532629739.602",
//   "SamplesPerPixel": "1",
//   "SaturationPlanes": null,
//   "ScanOptions": "FAST_GEMS\\SEQ_GEMS\\ART_GEMS\\PFF",
//   "ScannerStudyEntityUID": "1.2.276.0.38.1.1.1.12649.20180801063459.71351232",
//   "ScannerStudyID": "13071 ",
//   "ScannerTableEntry": "0\\0\\0\\0 ",
//   "ScanningSequence": "GR",
//   "ScoutType": null,
//   "ScreenFormat": null,
//   "SecondEcho": "0 ",
//   "SequenceVariant": "SS\\SK",
//   "SeriesCompleteFlag": null,
//   "SeriesContrast": null,
//   "SeriesDate": "20180801",
//   "SeriesDescription": "3Plane Loc SSFSE",
//   "SeriesFromWhichPrescribed": null,
//   "SeriesInstanceUID": "1.2.840.113619.2.410.4722639.4348271.18936.1532629476.528",
//   "SeriesNumber": "1",
//   "SeriesPlane": null,
//   "SeriesTime": "130104",
//   "ServiceId": "HU1039          ",
//   "SliceLocation": "-20",
//   "SliceOffsetOnFrequencyAxis": null,
//   "SliceThickness": "10",
//   "SlopInteger10ToSlopInteger17": "0\\0\\0\\0\\0\\0\\0\\4 ",
//   "SlopInteger6ToSlopInteger9": "0\\1073741824\\0\\0",
//   "SmallestImagePixelValue": "0",
//   "SoftwareVersions": "27\\LX\\MR Software release:DV25.1_R02_1649.a",
//   "SpacingBetweenSlices": "20",
//   "SpecificCharacterSet": "ISO_IR 101",
//   "StartTimeSecsInFirstAxial": null,
//   "StationName": "HSZRMR02",
//   "StringSlopField2": "",
//   "StudyDate": "20180801",
//   "StudyDescription": "KOPONYA SM",
//   "StudyID": "13071",
//   "StudyInstanceUID": "1.2.276.0.38.1.1.1.12649.20180801063459.71351232",
//   "StudyTime": "130104",
//   "SuiteId": "HSZR",
//   "SurfaceCoilType": null,
//   "SwapPhaseFrequency": null,
//   "SystemConfigurationInformation": "SRMode=120\\GCoilType=11\\gradientAmp=8921\\lineFreq=50\\RFampType=32 ",
//   "TableDelta": "0.000000",
//   "ThicknessDisclaimer": null,
//   "TransmitGain": "114 ",
//   "TransmittingCoil": null,
//   "TriggerWindow": "0",
//   "TypeOfReceiverUsed": null,
//   "UniqueImageIdentifier": null,
//   "Unknown Tag & Data": null,
//   "UpperRangeOfPixels": null,
//   "User25ToUser48": null,
//   "UserData": "0.000000",
//   "UserDefinedData": null,
//   "UserFillMapLSW": null,
//   "UserFillMapMSW": null,
//   "UserUsageTag": null,
//   "VariableEchoFlag": null,
//   "VariableFlipAngleFlag": "N",
//   "VelocityEncodeScale": "0.000000",
//   "VelocityEncoding": null,
//   "VersionOfHeaderStructure": null,
//   "ViewsPerSegment": null,
//   "WindowCenter": "1063",
//   "WindowValue": null,
//   "WindowWidth": "2126"
// }
// }
